### ISSUE TITLE
Transfer repo to TC39 org

### ISSUE THREAD

**Issue by ljharb** [tc39-transfer/ecmascript-binary-ast#64]
All stage 1+ proposals need to live in the tc39 org on github. Please follow the [transfer instructions](https://github.com/tc39/proposals#onboarding-existing-proposals) to move this repo to the appropriate place.

**Comment by syg** [comment]
Done.

**Comment by ljharb** [comment]
cc @leobalter @littledan @bterlson please carry this forward to the tc39 org

**Comment by sideshowbarker** [comment]
Shouldn’t the repo name be `proposal-binary-ast`? (The `proposal-` prefix seems to be the naming convention used for most other proposals repos under the tc39 github org…)

**Comment by ljharb** [comment]
ah yes, that'd be great - @syg, can you do that?
